sudo: required

services:
  - docker

before_install:
  - docker build -t priyanshrastogi/node-aws-travis-ci .

script:
  - docker run priyanshrastogi/node-aws-travis-ci npm test

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
  region: "ap-south-1"  
  app: "$APP_NAME"
  env: "$ENV_NAME"
  bucket_name: "$BUCKET_NAME"
  bucket_path: "$BUCKET_PATH"
  on:
    branch: master